const SITE={discord:{name:"BlackArch Discord",url:"https://discord.gg/aVdA3Kc6tZ"},clients:[
{name:"Augustus",ver:"B4.20.3",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/xiGc"},{name:"DineTire",ver:"",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/eeKa"},{name:"Skid",ver:"V12.13",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/YLZt"},{name:"Skid",ver:"V13.16",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/orGD"},{name:"Vape",ver:"B4.17",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/XfiB"},{name:"LiquidBounce",ver:"B100",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/FHxF"},{name:"MoonLight",ver:"B3.3.6",mc:"1.8.8",desc:"Legacy client archive",url:"https://linkget.ru/hnvy"},
{name:"Monoton",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/uMUO"},{name:"DimasikClient",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/Ecdz"},{name:"DimasikClient LAST",ver:"",mc:"1.16.5",desc:"Last release",url:"https://linkget.ru/LLgN"},{name:"Eviscerate",ver:"",mc:"1.12.2",desc:"Client archive",url:"https://linkget.ru/nubM"},{name:"Catlavan",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/HTay"},{name:"Catlavan LAST",ver:"",mc:"1.16.5",desc:"Last release",url:"https://linkget.ru/Wyud"},{name:"Celestial",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/bAGN"},{name:"Nursultan",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/VESN"},{name:"Nuclear",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/xlcl"},{name:"Wexside",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/ZciO"},{name:"Vessence",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/cLnn"},{name:"Expensive",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/qeZn"},{name:"EnergyClient",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/aQEV"},{name:"Essence",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/ENig"},{name:"EvaWare",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/JZnK"},{name:"Rockstar",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/SQWX"},{name:"Refacus",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/QWMA"},{name:"SystemDLC",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/wDUy"},{name:"Aspect",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/QPgk"},{name:"QuickClient",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/chjb"},{name:"PrivateDLC",ver:"",mc:"1.16.5",desc:"Client archive",url:"https://linkget.ru/YcuK"},{name:"Zenith",ver:"",mc:"1.21.4",desc:"Client archive",url:"https://linkget.ru/OwiE"},
{name:"Laze",ver:"DLL",mc:"Other",desc:"Inject .dll",url:"https://linkget.ru/sFzO"},{name:"Slinky",ver:"BAT",mc:"Other",desc:"Start .bat",url:"https://linkget.ru/AQgb"},{name:"Vape",ver:"B4.17",mc:"Other",desc:"Inject .dll",url:"https://linkget.ru/AiCC"},{name:"Vape",ver:"B4.18",mc:"Other",desc:"Start .bat",url:"https://linkget.ru/AQZX"}
]};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=t=>{const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove("show"),2200)};
const clientGrid=$("#clientGrid"),empty=$("#empty"),search=$("#search");let filter="all";
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function renderClients(){const q=search.value.trim().toLowerCase();const list=SITE.clients.filter(c=>(filter==="all"||(filter==="other"?c.mc==="Other":c.mc===filter||((filter==="1.12.2+")&&c.mc!=="1.8.8"&&c.mc!=="Other")))&&(!q||(c.name+" "+c.ver+" "+c.mc).toLowerCase().includes(q)));clientGrid.innerHTML=list.map((c,i)=>`<article class="card" style="--delay:${Math.min(i,12)*35}ms"><div class="card-top"><span class="tag">${esc(c.mc)}</span><span class="index">${String(SITE.clients.indexOf(c)+1).padStart(2,"0")}</span></div><div class="client-symbol">${esc(c.name.slice(0,1).toUpperCase())}</div><h3>${esc(c.name)}</h3><p>${esc(c.desc)}${c.ver?` · ${esc(c.ver)}`:""}</p><a class="btn" target="_blank" rel="noopener" href="${esc(c.url)}">DOWNLOAD <span>↗</span></a></article>`).join("");empty.classList.toggle("show",!list.length);$("#clientCount").textContent=SITE.clients.length}
renderClients();search.addEventListener("input",renderClients);
$$("#filters button").forEach(b=>b.onclick=()=>{$$("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;renderClients()});
function show(id){if(!id||!/^[a-z]+$/.test(id)||!$("#"+id))id="clients";$$('.panel').forEach(p=>p.classList.toggle('on',p.id===id));$$('#tabs button').forEach(b=>b.classList.toggle('on',b.dataset.tab===id));history.replaceState(null,"","#"+id);scrollTo(0,0)}
$$("#tabs button").forEach(b=>b.onclick=()=>show(b.dataset.tab));
$("#discordCard").innerHTML=`<div class="hero-kicker">OFFICIAL COMMUNITY</div><div class="discord-symbol">◎</div><h2>${esc(SITE.discord.name)}</h2><p>Updates, releases and community discussion. Join the BlackArch network.</p><a class="btn" target="_blank" rel="noopener" href="${SITE.discord.url}">OPEN DISCORD <span>↗</span></a>`;
$("#cfgList").innerHTML=SITE.clients.filter(c=>c.mc!=="Other").slice(0,8).map(c=>`<div class="row"><i>${esc(c.mc)}</i><div><h3>${esc(c.name)}</h3><p>Configuration entry</p></div><span class="row-arrow">→</span></div>`).join("");
$("#steps").innerHTML=[['01','Choose a client','Select a release from the Clients tab using the version filters or search.'],['02','Open the download','Press DOWNLOAD. External download links open in a new tab.'],['03','Extract / install','Follow the release-specific instructions and keep your Minecraft version matched.'],['04','Launch','Start the client using its supplied launcher, loader or installation method.']].map(x=>`<li><strong>${x[0]}</strong><div><b>${x[1]}</b><span>${x[2]}</span></div></li>`).join('');
// boot sequence
const boot=$("#boot"),log=$("#bootlog"),bar=$("#bootbar"),pct=$("#bootpct"),status=$("#bootstatus");const lines=['mounting client archive','checking release index','loading interface modules','indexing client entries','connecting community layer','blackarch ready'];let n=0;function bootTick(){if(n<lines.length){log.innerHTML+=`<div><b>[ OK ]</b> ${lines[n]}</div>`;n++;const v=Math.round(n/lines.length*100);bar.style.width=v+'%';pct.textContent=v+'%';status.textContent=lines[Math.min(n,lines.length-1)]+'...';setTimeout(bootTick,180)}else{status.textContent='system ready';setTimeout(()=>boot.classList.add('done'),420)}};setTimeout(bootTick,350);
// card pointer glow
clientGrid.addEventListener('pointermove',e=>{const c=e.target.closest('.card');if(!c)return;const r=c.getBoundingClientRect();c.style.setProperty('--mx',e.clientX-r.left+'px');c.style.setProperty('--my',e.clientY-r.top+'px')});
show(location.hash.slice(1));
